name: Anya KSU+SUSFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo apt clean

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y git curl wget bc bison flex libssl-dev libelf-dev zip cpio

    - name: Setup google clang 22.0.1
      run: |
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/42d2c090c14c9c7f4dfd365ae551e2b959dc775c/clang-r584948b.tar.gz
        mkdir clang
        tar -zxf clang-r584948b.tar.gz -C clang
        rm -rf clang-r584948b.tar.gz

    - name: Clone android12-5.10-lts (GKI 5.10)
      run: |
        git clone --depth=1 https://github.com/ip2na/android12-5.10-lts.git kernel

    - name: Setup KernelSU Next + SUSFS
      run: |
        cd kernel
        # Setup KSU Next
        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s dev-susfs
        
        cd KernelSU-Next
        echo "KSU_COMMIT=$(git log -1 --pretty=format:"%s (%an)")" >> $GITHUB_ENV
        cd ..

        git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu -b gki-android12-5.10 .susfs
        cd .susfs
        echo "SUSFS_COMMIT=$(git log -1 --pretty=format:"%s (%an)")" >> $GITHUB_ENV
        cd ..
        
        kernel_patches="$(pwd)/.susfs/kernel_patches"
        cp -R $kernel_patches/fs/* ./fs
        cp -R $kernel_patches/include/* ./include
        patch -p1 < $kernel_patches/*.patch || true

    - name: Inject Config
      run: |
        cd kernel
        cat >> arch/arm64/configs/gki_defconfig << 'EOF'
        CONFIG_KSU=y
        CONFIG_KSU_MANUAL_HOOK=y
        CONFIG_KSU_LSM_SECURITY_HOOKS=y
        CONFIG_KSU_SUSFS=y
        CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
        CONFIG_KSU_SUSFS_SUS_PATH=y
        CONFIG_KSU_SUSFS_SUS_MOUNT=y
        CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
        CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
        CONFIG_KSU_SUSFS_SUS_KSTAT=y
        CONFIG_KSU_SUSFS_TRY_UMOUNT=y
        CONFIG_KSU_SUSFS_ENABLE_LOG=y
        CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
        CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
        CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
        # CONFIG_KSU_SUSFS_SPOOF_UNAME is not set
        CONFIG_MTK_CPU_FREQ=y
        CONFIG_MTK_CPU_DVFS=y
        CONFIG_MTK_SUSPEND=y
        CONFIG_MTK_VCORE_DVFS=y
        CONFIG_MTK_IDLE_BALANCE=y
        CONFIG_MTK_SCHED_DVFS=y
        CONFIG_ZRAM=y
        CONFIG_ZRAM_WRITEBACK=y
        CONFIG_ZSWAP=y
        CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL=y
        CONFIG_SCHED_TUNE=y
        # CONFIG_PREEMPT_VOLUNTARY is not set
        # CONFIG_PREEMPT_NONE is not set 
        EOF

    - name: Build Kernel
      run: |
        cd kernel
        export PATH="$(pwd)/../clang/bin:$PATH"
        export KBUILD_BUILD_USER="builder-dev"
        export KBUILD_BUILD_HOST="Anyaanasera"
        make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out CROSS_COMPILE=aarch64-linux-gnu- gki_defconfig
        make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) Image

    - name: Generate Build Info
      run: |
        cd kernel
        echo "BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
        echo "COMMIT=$(git log -1 --pretty=format:"%s (%an)")" >> $GITHUB_ENV
        echo "KERNEL_VER=$(cat out/include/generated/utsrelease.h | sed 's/.*"\(.*\)".*/\1/')" >> $GITHUB_ENV
        echo "COMPILER=$($GITHUB_WORKSPACE/clang/bin/clang --version | head -n 1)" >> $GITHUB_ENV
        echo "DATE=$(date "+%d%m%y")" >> $GITHUB_ENV

    - name: Clone AnyKernel3 Custom
      run: |
        git clone --depth=1 -b gki-2.0 https://github.com/ip2na/AnyKernel3.git ak3

    - name: Copy Image
      run: |
        cp kernel/out/arch/arm64/boot/Image ak3/

    - name: Pack ZIP
      run: |
        cd ak3
        zip -r9 Kernel-KSU-SUSFS.zip * -x "*.git*" -x "*.github*"

    - name: Upload to Telegram
      run: |
       cd ak3
       cat > caption.txt << EOF
       🌱 Branch: $BRANCH
       🐧 Linux version: $KERNEL_VER
       📆 Build date : $DATE
       ♻️ Latest commit: $COMMIT
       🔐 KSU commit: $KSU_COMMIT
       🛡️ SUSFS commit: $SUSFS_COMMIT
       ⚙️ Compiler: $COMPILER

       #Anyakernel #update #gki-5.10 #ksu #susfs
       EOF
       curl --fail -F document=@Kernel-KSU-SUSFS.zip \
       -F "caption=< caption.txt" \
       "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.CHAT_ID }}"
