name: Build GKI 5.10 KSU SUSFS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4
      
    - name: 💾 Free Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo apt clean

    - name: 🧰 Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git curl wget bc bison flex \
          libssl-dev libelf-dev zip cpio
          
    - name: ⚡ Setup Clang r498229 (LLVM 17)
      run: |
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/ba7da711271d310dda6b5134d8f4448f6a276a27/clang-r498229b.tar.gz
        mkdir clang
        tar -zxf clang-r498229b.tar.gz -C clang
        rm -rf clang-r498229b.tar.gz

    # SOURCE KERNEL
    - name: 📦 Clone Kernel
      run: |
        git clone --depth=1 https://github.com/ip2na/android12-5.10-lts.git kernel

    # KSU NEXT + SUSFS
    - name: 🔥 Setup KernelSU Next + SUSFS
      run: |
        cd kernel

        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s dev-susfs

        git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu -b gki-android12-5.10 .susfs

        kernel_patches="$(pwd)/.susfs/kernel_patches"

        cp -R $kernel_patches/fs/* ./fs
        cp -R $kernel_patches/include/* ./include

        patch -p1 < $kernel_patches/*.patch || true

    # FIX DEFCONFIG
    - name: Inject Config
      run: |
        cd kernel
        
        cat >> arch/arm64/configs/gki_defconfig << 'EOF'

           
        CONFIG_KSU=y
        CONFIG_KSU_MANUAL_HOOK=y
        CONFIG_KSU_LSM_SECURITY_HOOKS=y
       
        CONFIG_KSU_SUSFS=y
        CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
        CONFIG_KSU_SUSFS_SUS_PATH=y
        CONFIG_KSU_SUSFS_SUS_MOUNT=y
        CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
        CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
        CONFIG_KSU_SUSFS_SUS_KSTAT=y
        CONFIG_KSU_SUSFS_TRY_UMOUNT=y
        CONFIG_KSU_SUSFS_ENABLE_LOG=y
        CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
        CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
        CONFIG_KSU_SUSFS_OPEN_REDIRECT=y 
        # CONFIG_KSU_SUSFS_SPOOF_UNAME is not set
        CONFIG_MTK_CPU_FREQ=y
        CONFIG_MTK_CPU_DVFS=y
        CONFIG_MTK_SUSPEND=y
        CONFIG_MTK_VCORE_DVFS=y
        CONFIG_MTK_IDLE_BALANCE=y
        CONFIG_MTK_SCHED_DVFS=y
        # CONFIG_PREEMPT_VOLUNTARY is not set
        # CONFIG_PREEMPT_NONE is not set 

        CONFIG_ZRAM=y
        CONFIG_ZRAM_WRITEBACK=y
        CONFIG_ZSWAP=y
       
        CONFIG_CPU_FREQ_DEFAULT_GOV_SCHEDUTIL=y
        CONFIG_SCHED_TUNE=y
       
        EOF

    # 🏗️ BUILD
    - name: 🏗️ Build Kernel
      run: |
        cd kernel
        export PATH="$(pwd)/../clang/bin:$PATH"
        export KBUILD_BUILD_USER="builder-ghc"
        export KBUILD_BUILD_HOST="user"

        make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out CROSS_COMPILE=aarch64-linux-gnu- gki_defconfig
        make ARCH=arm64 LLVM=1 LLVM_IAS=1 O=out CROSS_COMPILE=aarch64-linux-gnu- -j$(nproc) Image


    # 📦 ANYKERNEL (PUNYA KAMU)
    - name: 📦 Clone AnyKernel3 Custom
      run: |
        git clone --depth=1 -b gki-2.0 https://github.com/ip2na/AnyKernel3.git ak3

    - name: 📥 Copy Image
      run: |
        cp kernel/out/arch/arm64/boot/Image ak3/

    # 📦 PACK ZIP
    - name: 📦 Pack ZIP
      run: |
        cd ak3
        zip -r9 Kernel-KSU-SUSFS.zip * -x "*.git*" -x "*.github*"

    # 🔐 CHECKSUM
    - name: 🔐 Generate SHA256
      run: |
        cd ak3
        sha256sum Kernel-KSU-SUSFS.zip > checksum.txt

    - name: 📤 Upload to Telegram
      run: |
       cd ak3
       
          if [ ! -f "Kernel-KSU-SUSFS.zip" ]; then
          echo "Error: Kernel-KSU-SUSFS.zip tidak ditemukan!"
          exit 1
         fi
         
         if [ ! -f "checksum.txt" ]; then
         echo "Error: checksum.txt tidak ditemukan!"
         exit 1
         fi 
         
         if [ -z "${{ secrets.BOT_TOKEN }}" ] || [ -z "${{ secrets.CHAT_ID }}" ]; then
         echo "Error: BOT_TOKEN atau CHAT_ID belum diset di repository secrets!"
         exit 1
         fi
         
         curl --fail -F document=@Kernel-KSU-SUSFS.zip \
         -F caption="Build Success GKI 5.10 KSU Next + SUSFS ThinLTO\n\n$(cat checksum.txt)" \
         "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.CHAT_ID }}"
