name: Cherry-pick Commit

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to cherry-pick'
        required: true
        default: '45381182fd38ebcb446c037f25ed073e11f7fc6d'
      source_repo:
        description: 'Source repo URL'
        required: true
        default: 'https://github.com/Steambot12/Templar-Kernel-GKI-5.10/'

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git config
        run: |
          git config --global user.name "anyaanasera"
          git config --global user.email "anyaprjkt.my.id"

      - name: Add source remote & fetch
        run: |
          git remote add source ${{ github.event.inputs.source_repo }}
          git fetch source

      - name: Cherry-pick commit
        run: |
          git cherry-pick ${{ github.event.inputs.commit_sha }}

      - name: Push result
        run: |
          git push origin HEAD
