name: Cherry-pick 

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to cherry-pick'
        required: true
        default: '4e6853851fea9587fd7baba66972c416acf05db4'
      source_repo:
        description: 'Source repo URL'
        required: true
        default: 'https://github.com/Steambot12/Templar-Kernel-GKI-5.10/'
      target_repo:
        description: 'Target repo (owner/repo)'
        required: true
        default: 'ip2na/android12-5.10-lts'
      target_branch:
        description: 'Target branch'
        required: true
        default: 'main'

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Clone target repo
        run: |
          git clone https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.event.inputs.target_repo }}.git target
          cd target
          git checkout ${{ github.event.inputs.target_branch }}

      - name: Set git config
        run: |
          git config --global user.name "anyaanasera"
          git config --global user.email "anyaprjkt.my.id"

      - name: Add source remote & fetch
        working-directory: target
        run: |
          git remote add source ${{ github.event.inputs.source_repo }}
          git fetch source

      - name: Cherry-pick commit
        working-directory: target
        run: |
          git cherry-pick ${{ github.event.inputs.commit_sha }}

      - name: Push to target repo
        working-directory: target
        run: |
          git push origin ${{ github.event.inputs.target_branch }}
